### ISSUE TITLE
RunTime Error  

### ISSUE THREAD

**Issue by parekhpatel** [TuSDK/TuSDK-for-Android-demo#2]
This error will occur in project run  
CreateProcess error=2, The system cannot find the file specified ..
please give me solution..

**Comment by idealhack** [comment]
Could you paste more logs from logcat?

**Comment by parekhpatel** [comment]
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':TuSDKUIDefault:transformNativeLibsWithStripDebugSymbolForRelease'

Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)

**Comment by idealhack** [comment]
Are you running the demo app?

Please open a ticket at https://tutucloud.com/console for support. Thanks.

**Comment by idealhack** [comment]
@parekhpatel If you still could not find a clue after you check out our website, feel free to reopen this issue.
